### ISSUE TITLE
Italian Translations

### ISSUE THREAD

**Issue by p365labs** [jawache/principles-green#48]
Hi @jawache  @sebasrivera96 what if I add Italian translation? Is it ok for you?

**Comment by sebasrivera96** [comment]
I will defer this question to @jawache, but I think this page will soon be deprecated. The new "source-of-truth" will be the Green Practitioner Training: http://learn.greensoftware.foundation/.

**Comment by p365labs** [comment]
ok thank u!

**Comment by jawache** [comment]
Ahh yes, that's the new version and this site will be dereciated and forwarded to that one. The other is still open source however I don't believe we'll be accepting translations just yet, not till we have a process to keep everything updated!
